mallform/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using mallform.Models;
using mallform.ViewModel;
using System.IO;

namespace mallform.Controllers
{

    public class HomeController : Controller
    {
        private ApplicationDbContext _Context;
        public HomeController()
        {
            _Context = new ApplicationDbContext();
        }
        public ActionResult Index()
        {
            

                var tenant = _Context.Tenant;
            if (User.IsInRole("CanManageLeaseStatus"))

                return View("Index",tenant);
                return View("ReadOnlyTenant",tenant);

            
        }

        public ActionResult unitList()
        {
            var unit = _Context.Unit.Include(f=>f.Floor).Include(s=>s.Shop).ToList();
            if (User.IsInRole("CanManageLeaseStatus"))
            return View("unitList",unit);
            return View("ReadOnlyUnit", unit);
        }

        public ActionResult leaseStatus()
        {
            var leaseStatus = _Context.Rent./*Include(s=>s.Shop).*/Include(t => t.Tenant).ToList();
            if (User.IsInRole("CanManageLeaseStatus"))
               
            return View("leaseStatus",leaseStatus);
            return View("ReadOnlyLease", leaseStatus);


        }

        public ActionResult invoiceList()
        {
            var invoice = _Context.Invoice.Include(r => r.Rent.Tenant).ToList();
            if (User.IsInRole("CanManageLeaseStatus"))
            return View("invoiceList",invoice);
            return View("ReadOnlyInvoice", invoice);
        }
       

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

       
    }
}

mallform/Controllers/LeasingFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using mallform.Models;
using mallform.ViewModel;

namespace mallform.Controllers
{
    public class LeasingFormController : Controller
    {
        // GET: LeasingForm
        private ApplicationDbContext _context;

        public LeasingFormController()
        {

            _context = new ApplicationDbContext();
        }
        public ActionResult Form()
        {

           

            return View();
        }
        
        [HttpPost]
        public ActionResult Form(TenantFormViewModel Form)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", Form);

            }

                var tenant = new Tenant
            {
                shopName = Form.shopName,
                brandName = Form.brandName,
                Address = Form.Address,
                mobileNo = Form.mobileNo,
                panNo = Form.panNo
            };


           
                _context.Tenant.Add(tenant);

                _context.SaveChanges();

            
            return RedirectToAction("Index", "Home");
        }


        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Update (int id)
        {

            

            return View(_context.Tenant.Find(id));
        }


        [HttpPost]

        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Update (Tenant Model)
        {
         
            Tenant tenant = _context.Tenant.Where(m => m.Id == Model.Id).SingleOrDefault();
            if(tenant!=null)
            {

                _context.Entry(tenant).CurrentValues.SetValues(Model);
                _context.SaveChanges();

                return RedirectToAction("Index", "Home");

            }

            return View(Model);
        

        }
        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Delete (int id)
        {

            _context.Tenant.Remove(_context.Tenant.Find(id));
            _context.SaveChanges();

            return RedirectToAction("Index" , "Home");

        }




    }
}

mallform/Controllers/RentController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using mallform.Models;
using mallform.ViewModel;
using System.IO;
using System.Web.UI.WebControls; //for word document grid view
using System.Web.UI;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.text.html.simpleparser;
using iTextSharp.tool.xml;
using System.Text;
using iTextSharp.text.pdf.draw;
using System.Data;
using Microsoft.AspNet.Identity;

namespace mallform.Controllers
{
    public class RentController : Controller
    {
        private ApplicationDbContext _Context;


        public RentController()
        {
            _Context = new ApplicationDbContext();
        }
        //GET VALUES FROM THE DATABASE
        public ActionResult leaseUnit()
        {

            var tenants = _Context.Tenant.ToList();
          
            //var shops = _Context.Shop.ToList();


            var viewModel = new RentFormViewModel
            {
                Tenants = tenants,        
                //Shops = shops



            };

            return View("leaseUnit", viewModel);
        }


        [HttpPost]
        public ActionResult Save(Rent Rent, Models.FileUpload upload, HttpPostedFileBase file )
        {
            //if (_Context.Rent.Any(u => u.Id != Rent.Id && u.shopId == Rent.shopId))
            //{
            //    return Content("shop already occupied");



            //}

            Rent.totalAmount = 0;

           Rent.totalAmount  = Rent.Amount - ((Rent.Amount * Rent.Discount) / 100);

                if (Rent.Id == 0) {
                _Context.Rent.Add(Rent);
            }

            else
            {
               
                var rentInDb = _Context.Rent.Single(c => c.Id == Rent.Id);

                rentInDb.tenantId = Rent.tenantId;
                //rentInDb.unitId = Rent.unitId;
                rentInDb.startDate = Rent.startDate;
                rentInDb.endDate = Rent.endDate;
                rentInDb.Amount = Rent.Amount;
                rentInDb.leaseStatus = Rent.leaseStatus;
                rentInDb.totalAmount = Rent.totalAmount;
                rentInDb.IsDiscountGiven = Rent.IsDiscountGiven;
                //rentInDb.shopId = Rent.shopId;
                                      }

            _Context.SaveChanges();

            var rent = _Context.Rent.Single(r => r.Id == Rent.Id);

            var up = Request.Files["file"];
            if (up.ContentLength > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var guid = Guid.NewGuid().ToString();
                var path = Path.Combine(Server.MapPath("~/Rent"), fileName);
                file.SaveAs(path);
                string fl = path.Substring(path.LastIndexOf("\\"));
                string[] split = fl.Split('\\');
                string newpath = split[1];
                string imagepath = newpath;
                upload.length = imagepath;
                upload.Rent = rent;
                _Context.FileUpload.Add(upload);
                _Context.SaveChanges();
            }
            return RedirectToAction("leaseStatus", "Home");
        }

        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Edit(int id)

        {

            var Rent = _Context.Rent.SingleOrDefault(r => r.Id == id);


            if (Rent == null)
                return HttpNotFound();

            var viewModel = new RentFormViewModel
            {
                Tenants = _Context.Tenant.ToList(),
                Units = _Context.Unit.ToList(),
                Rent = Rent

            };


            return View("editLease", viewModel);
        }
        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Delete(int id)
        {
           
                _Context.Rent.Remove(_Context.Rent.Find(id));

                _Context.SaveChanges();
            
            return RedirectToAction("leaseStatus", "Home");
        }


        //  public ActionResult Details (int id)
        // {

        //    var Details = _Context.Rent.Include(u => u.Unit).Include(t => t.Tenant).SingleOrDefault(d => d.Id == id);

        //    return View(Details);


        // }

        public ActionResult Downloads(int id)
        {
            var fl = _Context.FileUpload.Where(f => f.rentId == id);
            var up = Request.Files["file"];




            return View(fl);
        }

        public FileResult Download(string ImageName)
        {
            var FileVirtualPath = Server.MapPath("" + ImageName);

            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));


        }


        public ActionResult Details(int id)
        {

            var Details = _Context.Rent/*.Include(u => u.Unit)*/.Include(t => t.Tenant).SingleOrDefault(d => d.Id == id);

            return View(Details);


        }


        //protected void Print(object sender, EventArgs e)
        //{
        //    var invoice = _Context.Invoice.FirstOrDefault();

        //    //Dummy data for Invoice (Bill).
        //    string heading = "Vikram";
        //    int InvoiceNo = 2303;
        //    DataTable dt = new DataTable();
        //    dt.Columns.AddRange(new DataColumn[5] {
        //                    new DataColumn("Tenant", typeof(string)),
        //                    new DataColumn("Start Month", typeof(string)),
        //                    new DataColumn("End Month", typeof(int)),
        //                    new DataColumn("Discount", typeof(int)),
        //                    new DataColumn("Total Amount", typeof(int))});
        //    dt.Rows.Add(101,invoice.InvoiceStatus, 200, 5, 1000);
        //    dt.Rows.Add(102, invoice.startMonth, 400, 2, 800);
        //    dt.Rows.Add(103, invoice.endMonth, 300, 3, 900);
        //    dt.Rows.Add(104, invoice.invoiceDiscount, 550, 2, 1100);

        //    using (StringWriter sw = new StringWriter())
        //    {
        //        using (HtmlTextWriter hw = new HtmlTextWriter(sw))
        //        {
        //            StringBuilder sb = new StringBuilder();

        //            //Generate Invoice (Bill) Header.
        //            sb.Append("<table width='100%' cellspacing='0' cellpadding='2'>");
        //            sb.Append("<tr><td align='center' style='background-color: #18B5F0' colspan = '2'><b>Invoice Has Been Generated</b></td></tr>");
        //            sb.Append("<tr><td colspan = '2'></td></tr>");
                   
        //            sb.Append("</td><td align = 'right'><b>Date: </b>");
        //            sb.Append(DateTime.Now);
        //            sb.Append(" </td></tr>");
        //            sb.Append("<tr><td colspan = '2'><b>Invoice By: </b>");
        //            sb.Append(heading);
        //            sb.Append("</td></tr>");
        //            sb.Append("</table>");
        //            sb.Append("<br />");

        //            //Generate Invoice (Bill) Items Grid.
        //            sb.Append("<table border = '1'>");
        //            sb.Append("<tr>");
        //            foreach (DataColumn column in dt.Columns)
        //            {
        //                sb.Append("<th style = 'background-color: #D20B0C;color:#ffffff'>");
        //                sb.Append(column.ColumnName);
        //                sb.Append("</th>");
        //            }
        //            sb.Append("</tr>");
        //            foreach (DataRow row in dt.Rows)
        //            {
        //                sb.Append("<tr>");
        //                foreach (DataColumn column in dt.Columns)
        //                {
        //                    sb.Append("<td>");
        //                    sb.Append(row[column]);
        //                    sb.Append("</td>");
        //                }
        //                sb.Append("</tr>");
        //            }
        //            sb.Append("<tr><td align = 'right' colspan = '");
        //            sb.Append(dt.Columns.Count - 1);
        //            sb.Append("'>Total</td>");
        //            sb.Append("<td>");
        //            sb.Append(dt.Compute("sum(Total)", ""));
        //            sb.Append("</td>");
        //            sb.Append("</tr></table>");

        //            //Export HTML String as PDF.
        //            StringReader sr = new StringReader(sb.ToString());
        //            Document pdfDoc = new Document(PageSize.A4, 10f, 10f, 10f, 0f);
        //            XMLWorker htmlparser = new XMLWorkerH(pdfDoc);
        //            PdfWriter writer = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
        //            pdfDoc.Open();
        //            htmlparser.Parse(sr);
        //            pdfDoc.Close();
        //            Response.ContentType = "application/pdf";
        //            Response.AddHeader("content-disposition", "attachment;filename=Invoice_" + InvoiceNo + ".pdf");
        //            Response.Cache.SetCacheability(HttpCacheability.NoCache);
        //            Response.Write(pdfDoc);
        //            Response.End();
        //        }
        //    }
        //}

        //[HttpPost]
        //[ValidateInput(false)]
        //public FileResult Print(string GridHtml)
        //{

        //    using (MemoryStream stream = new System.IO.MemoryStream())
        //    {
        //        StringReader sr = new StringReader(GridHtml);
        //        Document pdfDoc = new Document(PageSize.A4, 50f, 100f, 100f, 0f);
        //        PdfWriter writer = PdfWriter.GetInstance(pdfDoc, stream);
        //        pdfDoc.Open();

        //        Paragraph para = new Paragraph("YOUR INVOICE HAS BEEN GENERATED", new Font(Font.FontFamily.HELVETICA, 22));
        //        para.Alignment = Element.ALIGN_CENTER;
        //        pdfDoc.Add(para);

mallform/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using mallform.Models;
using mallform.ViewModel;
using System.Data.Entity;

namespace mallform.Controllers
{
    public class UnitController : Controller
    {
        public ApplicationDbContext _Context;

        public UnitController()
        {
            _Context = new ApplicationDbContext();

        }
        public ActionResult AddUnit() //GET UNITS 
        {
           
            var floors = _Context.Floor.ToList();
            var shops = _Context.Shop.ToList();
            var viewModel = new UnitFormViewModel
            {
                
                Floors = floors,
                Shops = shops
            };

            return View("AddUnit",viewModel);
        }

        //POST UNITS

        [HttpPost]
        public ActionResult Save( Unit Unit)
        {
          
            if (_Context.Unit.Any(u => u.Id != Unit.Id && u.shopId== Unit.shopId))
            {
                return Content("shop already occupied");
                   


            }
            if (Unit.Id == 0)
            {
                _Context.Unit.Add(Unit);
             
            }

           // if(Unit.Id > 0)
           // {
           //     ViewBag.Duplicate = "This Shop " + Unit.shopId + "is already in use";
          //  }

            else
            {
                var unitInDb = _Context.Unit.Single(c => c.Id == Unit.Id);

                unitInDb.Size = Unit.Size;
                unitInDb.floorId = Unit.floorId;
                unitInDb.shopId = Unit.shopId;
            }

            _Context.SaveChanges();

            return RedirectToAction("unitList", "Home");
        }






        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Edit(int id)

        {
            var Unit = _Context.Unit.SingleOrDefault(u => u.Id == id);
            if (Unit == null)
                return HttpNotFound();
            var viewModel = new UnitFormViewModel
            {
                Unit=Unit,
               Floors=_Context.Floor.ToList(),
                Shops = _Context.Shop.ToList()


            };
            return View("EditUnit", viewModel);
        }


        //DELETE A UNIT
        [Authorize(Roles = "CanManageLeaseStatus")]
        public ActionResult Delete(int id)

        {

            _Context.Unit.Remove(_Context.Unit.Find(id));

            _Context.SaveChanges();

            return RedirectToAction("unitList", "Home");

        }





    }
}

   

mallform/Views/Home/Index.cshtml
@model IEnumerable<mallform.Models.Tenant>

@{
    ViewBag.Title = "Home Page";
}

<h2><strong>Tenant List</strong></h2>
<br>
<br>
@Html.ActionLink("Add Tenant", "Form", "LeasingForm", null, new { @class = "btn btn-primary btn-large" })
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Shop Name</th>
            <th scope="col">Brand Name</th>
            <th scope="col">Address</th>
            <th scope="col">Contact No</th>
            <th scope="col">Pan No</th>
            
        </tr>
    </thead>

    @foreach (var tenant in Model)
    {



        <tbody>
            <tr>

                
                <td>@tenant.shopName</td>
                <td>@tenant.brandName</td>
                <td>@tenant.Address</td>
                <td>@tenant.mobileNo</td>
                <td>@tenant.panNo</td>
                <td>@Html.ActionLink("Edit Tenant", "Update", "LeasingForm", new { id = tenant.Id }, null) </td>
                <td>@Html.ActionLink("Delete", "Delete", "LeasingForm", new { id=tenant.Id },
    new { onclick = "return confirm('Are you sure you wish to delete this Tenant?');" })</td>
                
                
                    
               


              




            </tr>

        </tbody>





    }
</table>

   

mallform/Views/Home/ReadOnlyInvoice.cshtml
@model IEnumerable<mallform.Models.Invoice>
@{
    ViewBag.Title = "ReadOnlyInvoice";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Invoice List </h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Tenant</th>
            <th scope="col">Created On</th>
            <th scope="col">Start Month</th>
            <th scope="col">End Month</th>
            <th scope="col">Total Amount</th>
            <th scope="col">Status</th>
            <th scope="col">Description</th>


        </tr>
    </thead>

    @foreach (var invoice in Model)
    {

        <tbody>
            <tr>
                <td>
                    @invoice.Rent.Tenant.shopName
                </td>
                <td>
                    @invoice.CreatedDate.ToString("MM/dd/yyyy")
                </td>
                <td>
                    <div class="Date">

                        <div class="Month">
                            @invoice.startMonth.ToString("MMM")
                        </div>
                        <div class="day">
                            @invoice.startMonth.ToString("d ")
                        </div>

                    </div>
                </td>
                <td>
                    <div class="endDate">
                        <div class="MM">
                            @invoice.endMonth.ToString("MMM")
                        </div>
                        <div class="dd">
                            @invoice.endMonth.ToString("d ")
                        </div>
                    </div>
                </td>

                <td>
                    @invoice.Rent.Amount
                </td>
                <td>
                    @invoice.InvoiceStatus
                </td>
                <td>
                    @invoice.Discription
                </td>
                <td>

                    @Html.ActionLink("Print", "GenratePrint", "Rent", new { id = invoice.Id }, null)
                </td>

                

                

            </tr>
        </tbody>
    }
</table>

mallform/Views/Home/ReadOnlyLease.cshtml
@model IEnumerable<mallform.Models.Rent>
@{
    ViewBag.Title = "ReadOnlyLease";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>List of Active Leased Units</strong></h2>
<br>
@Html.ActionLink("Add Lease Status", "leaseUnit", "Rent", null, new { @class = "btn btn-primary btn-large" })

<div class="invoiceButton">
    @Html.ActionLink("Invoice List", "invoiceList", "Home", null, new { @class = "btn btn-primary btn-large" })


</div>
<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th scope="col">Tenant</th>
            <th scope="col">Size Chosen</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Status</th>


        </tr>
    </thead>

    @foreach (var Rent in Model)
    {

        <tbody>
            <tr>

                <td>
                    @Html.ActionLink(Rent.Tenant.shopName, "Details", "Rent", new { id = Rent.Id }, null)

                </td>
                <td>
                    @*@Rent.Unit.Size*@
                </td>

                <td>
                    <div class="Date">

                        <div class="Month">
                            @Rent.startDate.ToString("MMM")
                        </div>
                        <div class="day">
                            @Rent.startDate.ToString("d ")
                        </div>

                    </div>
                </td>
                <td>
                    <div class="endDate">
                        <div class="MM">
                            @Rent.endDate.ToString("MMM")
                        </div>
                        <div class="dd">
                            @Rent.endDate.ToString("d ")
                        </div>
                    </div>
                </td>
                <td>
                    <div class="money">

                        @Rent.Amount
                    </div>
                </td>

                <td>
                    <div class="leaseStatus">

                        @Rent.leaseStatus
                    </div>
                </td>





               
               


                <td>
                    @Html.ActionLink("Uploaded Files", "Downloads", "Rent", new { id = Rent.Id }, null)


                </td>

                <td>
                    @Html.ActionLink("Generate Invoice", "GenrateInvoice", "Rent", new { id = Rent.Id }, null)


                </td>






            </tr>
        </tbody>
    }
</table>

mallform/Views/Home/ReadOnlyTenant.cshtml
@model IEnumerable<mallform.Models.Tenant>
@{
    ViewBag.Title = "ReadOnlyTenant";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Home Page";
}
<h2><strong>Tenant List</strong></h2>
<br>
<br>
@Html.ActionLink("Add Tenant", "Form", "LeasingForm", null, new { @class = "btn btn-primary btn-large" })
<br>
<br>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Shop Name</th>
            <th scope="col">Brand Name</th>
            <th scope="col">Address</th>
            <th scope="col">Contact No</th>
            <th scope="col">Pan No</th>

        </tr>
    </thead>
    @foreach (var tenant in Model)
    {
        <tbody>
            <tr>

                <td>@tenant.shopName</td>
                <td>@tenant.brandName</td>
                <td>@tenant.Address</td>
                <td>@tenant.mobileNo</td>
                <td>@tenant.panNo</td>
              
        </tr>
    </tbody>

    }
</table>

mallform/Views/Home/ReadOnlyUnit.cshtml
@model IEnumerable<mallform.Models.Unit>
@{
    ViewBag.Title = "ReadOnlyUnit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>List of Units</strong></h2>
<br>

@Html.ActionLink("Add Unit", "AddUnit", "Unit", null, new { @class = "btn btn-primary btn-large" })
<br>
<br>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Shop Size (In Square Feet)</th>
            <th scope="col">Floor</th>
            <th scope="col">Shop Number</th>

        </tr>
    </thead>
    @foreach (var unit in Model)
    {



        <tbody class="leaseStatus">
            <tr>

                <td>@unit.Size</td>
                <td>@unit.Floor.Name</td>
                <td>@unit.Shop.Name</td>

        </tr>
    </tbody>

    }
</table>

mallform/Views/Home/invoiceList.cshtml
@model IEnumerable<mallform.Models.Invoice>
@{
    ViewBag.Title = "invoiceList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Invoice List </h2>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Tenant</th>
            <th scope="col">Created On</th>
            <th scope="col">Start Month</th>
            <th scope="col">End Month</th>
            <th scope="col">Discount</th>
            <th scope="col">Total Amount</th>
            <th scope="col">Status</th>
            <th scope="col">Description</th>          


        </tr>
    </thead>

    @foreach (var invoice in Model)
    {

        <tbody>
            <tr>
                <td>
                    @invoice.Rent.Tenant.shopName
                </td>
                <td>
                    @invoice.CreatedDate.ToString("MM/dd/yyyy")
                </td>
                <td>
                    <div class="Date">

                        <div class="Month">
                            @invoice.startMonth.ToString("MMM")
                        </div>
                        <div class="day">
                            @invoice.startMonth.ToString("d ")
                        </div>

                    </div>
                </td>
                <td>
                    <div class="endDate">
                        <div class="MM">
                            @invoice.endMonth.ToString("MMM")
                        </div>
                        <div class="dd">
                            @invoice.endMonth.ToString("d ")
                        </div>
                    </div>
                </td>
                <td>
                    @invoice.invoiceDiscount %
                </td>
                <td>
                  @invoice.totalAmount Rs
                </td>
                <td>
                    @invoice.InvoiceStatus
                </td>
                <td>
                    @invoice.Discription
                </td>
                <td>

                    @Html.ActionLink("Print", "GenratePrint", "Rent", new { id = invoice.Id }, null)
                </td>


                <td>@Html.ActionLink("Edit", "EditInvoice", "Rent", new { id = invoice.Id }, null)</td>

                <td>
                    @Html.ActionLink("Delete", "DeleteInvoice", "Rent", new { id = invoice.Id },
 new { onclick = "return confirm('Are you sure you wish to delete this Detail?');" })

                </td>

            </tr>
        </tbody>
    }
</table>

mallform/Views/Home/leaseStatus.cshtml
@model IEnumerable<mallform.Models.Rent>
@{
    ViewBag.Title = "leaseStatus";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>List of Active Leased Units</strong></h2>
<br>
@Html.ActionLink("Add Lease Status", "leaseUnit", "Rent", null, new { @class = "btn btn-primary btn-large" })

<div class="invoiceButton">
   
        @Html.ActionLink("Invoice List", "invoiceList", "Home", null, new { @class = "btn btn-primary btn-large" })

    
</div>
<br />
<br />
<table class="table">
    <thead>
        <tr>
            <th scope="col">Tenant</th>
            <th scope="col">Size Chosen</th>
            <th scope="col">Start Date</th>
            <th scope="col">End Date</th>
            <th scope="col">Amount</th> 
            <th scope="col">Discount Rate</th> 
            <th scope="col">Total Amount</th>
            <th scope="col">Status</th>    
            

        </tr>
    </thead>
    
        @foreach (var Rent in Model)
        {

            <tbody>
                <tr>

                    <td>
                      @Html.ActionLink(Rent.Tenant.shopName , "Details", "Rent", new { id = Rent.Id }, null)

                    </td>
                    @*<td>
                        @Rent.Shop.Name 
                    </td>*@
 
                    <td>
                        <div class="Date">

                            <div class="Month">
                                @Rent.startDate.ToString("MMM")
                            </div>
                            <div class="day">
                                @Rent.startDate.ToString("d ")
                            </div>

                        </div>
                    </td>
                    <td>
                        <div class="endDate">
                            <div class="MM">
                                @Rent.endDate.ToString("MMM")
                            </div>
                            <div class="dd">
                                @Rent.endDate.ToString("d ")
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class= "money">

                            @Rent.Amount Rs
                        </div>
                    </td> 
                    <td>
                        @Rent.Discount %
                    </td>

                    <td>
                        @Rent.totalAmount Rs
                    </td>

                    <td>
                        <div class="leaseStatus">

                            @Rent.leaseStatus
                        </div>
                    </td>

                    
                    
                   
                   
                    <td>@Html.ActionLink("Edit", "Edit", "Rent", new { id = Rent.Id },null)</td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", "Rent", new { id = Rent.Id  },
 new { onclick = "return confirm('Are you sure you wish to delete this Detail?');" })
                </td>

                   
                    <td>
                        @Html.ActionLink("Uploaded Files", "Downloads", "Rent", new { id = Rent.Id }, null)


                    </td>

                    <td>
                        @Html.ActionLink("Generate Invoice", "GenrateInvoice", "Rent", new { id = Rent.Id }, null)


                    </td>
                  


                    

                
                    
            </tr>
            </tbody>
        }
</table>

mallform/Views/Home/unitList.cshtml
@model IEnumerable<mallform.Models.Unit>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2><strong>List of Units</strong></h2>
<br>

    @Html.ActionLink("Add Unit", "AddUnit", "Unit", null, new { @class = "btn btn-primary btn-large" })
<br>
<br>


<table class="table">
    <thead>
        <tr>
            <th scope="col">Shop Size (In Square Feet)</th>
            <th scope="col">Floor</th>
            <th scope="col">Shop Number</th>
         
        </tr>
    </thead>
    @foreach (var unit in Model)
    {



        <tbody class="leaseStatus">
            <tr>
                
                <td>@unit.Size Sqft</td>
                <td>@unit.Floor.Name</td>
                <td>@unit.Shop.Name</td>
                <td>@Html.ActionLink("Edit Unit", "Edit", "Unit", new { id = unit.Id }, null)</td>
                <td>@Html.ActionLink("Delete", "Delete", "Unit", new { id =unit.Id }, 
    new { onclick = "return confirm('Are you sure you wish to delete this Unit?');" })</td>
               
     
            </tr>
        </tbody>

    }
</table>